// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Y-titcXTdhiumgBMQXtjzE7n6Z_v8gA',
    appId: '1:180123369212:web:fd4801705eff9d51272179',
    messagingSenderId: '180123369212',
    projectId: 'myfirstflutterproject-c2b3b',
    authDomain: 'myfirstflutterproject-c2b3b.firebaseapp.com',
    storageBucket: 'myfirstflutterproject-c2b3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChnuqKGI0BsuSFEBmuxwYKKuV9AWJ2fko',
    appId: '1:180123369212:android:c24b4d90273ab3f7272179',
    messagingSenderId: '180123369212',
    projectId: 'myfirstflutterproject-c2b3b',
    storageBucket: 'myfirstflutterproject-c2b3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK04afSZxbxvn-kTi9c3I38Facg3TLz-M',
    appId: '1:180123369212:ios:36784d24cc2e00e0272179',
    messagingSenderId: '180123369212',
    projectId: 'myfirstflutterproject-c2b3b',
    storageBucket: 'myfirstflutterproject-c2b3b.appspot.com',
    iosClientId: '180123369212-clohsasr4im9sv3gie9ivot26adumj7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK04afSZxbxvn-kTi9c3I38Facg3TLz-M',
    appId: '1:180123369212:ios:36784d24cc2e00e0272179',
    messagingSenderId: '180123369212',
    projectId: 'myfirstflutterproject-c2b3b',
    storageBucket: 'myfirstflutterproject-c2b3b.appspot.com',
    iosClientId: '180123369212-clohsasr4im9sv3gie9ivot26adumj7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
